### ISSUE TITLE
libconflate installs headers to wrong location by default

### ISSUE THREAD

**Issue by ingenthr** [membase/libconflate#4]
~/src/proxybuild/libconflate$ sudo make install
make  install-recursive
make[1]: Entering directory `/home/ubuntu/src/proxybuild/libconflate'
Making install in .
make[2]: Entering directory`/home/ubuntu/src/proxybuild/libconflate'
make[3]: Entering directory `/home/ubuntu/src/proxybuild/libconflate'
test -z "/usr/local/lib" || /bin/mkdir -p "/usr/local/lib"
 /usr/bin/install -c -m 644 'libconflate.a' '/usr/local/lib/libconflate.a'
 ranlib '/usr/local/lib/libconflate.a'
test -z "/usr/local/include/memcached" || /bin/mkdir -p "/usr/local/include/memcached"
 /usr/bin/install -c -m 644 'conflate.h' '/usr/local/include/memcached/conflate.h'
make[3]: Leaving directory`/home/ubuntu/src/proxybuild/libconflate'
make[2]: Leaving directory `/home/ubuntu/src/proxybuild/libconflate'
Making install in tests
make[2]: Entering directory`/home/ubuntu/src/proxybuild/libconflate/tests'
make[3]: Entering directory `/home/ubuntu/src/proxybuild/libconflate/tests'
make[3]: Nothing to be done for`install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.
make[3]: Leaving directory`/home/ubuntu/src/proxybuild/libconflate/tests'
make[2]: Leaving directory `/home/ubuntu/src/proxybuild/libconflate/tests'
make[1]: Leaving directory`/home/ubuntu/src/proxybuild/libconflate'

**Comment by dustin** [comment]
I don't understand why you'd see this.  the term 'memcached' doesn't seem to be anywhere in any of this code.

**Comment by ingenthr** [comment]
looks like it's come from the configure.ac, i'll get it fixed
