### ISSUE TITLE
libconflate does not build on Ubuntu due to incompatible pointer tpe

### ISSUE THREAD

**Issue by ingenthr** [membase/libconflate#6]
make[3]: Entering directory `/home/ubuntu/src/proxybuild/libconflate/tests'
make[3]:`check_kvpair' is up to date.
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..   -I/home/ubuntu/src/proxybuild/libstrophe  -g -O2 -Wall -Werror -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -MT check_xmpp-check_xmpp.o -MD -MP -MF .deps/check_xmpp-check_xmpp.Tpo -c -o check_xmpp-check_xmpp.o `test -f 'check_xmpp.c' || echo './'`check_xmpp.c
cc1: warnings being treated as errors
check_xmpp.c: In function ‘init_config’:
check_xmpp.c:41: warning: assignment from incompatible pointer type
make[3]: **\* [check_xmpp-check_xmpp.o] Error 1
make[3]: Leaving directory `/home/ubuntu/src/proxybuild/libconflate/tests'
make[2]: *** [check-am] Error 2
make[2]: Leaving directory`/home/ubuntu/src/proxybuild/libconflate/tests'
make[1]: **\* [check-recursive] Error 1
make[1]: Leaving directory `/home/ubuntu/src/proxybuild/libconflate'
make: **\* [check] Error 2

**Comment by dustin** [comment]
Fix for new log signature.

I need to enable test-on-commit again...

Closed by 7c66782055c5017255e73f3290895a3b80d36fe2
